[build]
builder = "nixpacks"
buildCommand = "./railway-build.sh"

[deploy]
startCommand = "./main"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PORT = "8080"
RAILWAY_ENVIRONMENT_NAME = "production"
CGO_ENABLED = "1"
DATABASE_PATH = "/data/game.db" 